"""The benchmark. Every number in the README table comes from here.

Run it with no arguments and it prints a table and writes bench/results.json;
run one section alone and it merges into the same file:

    python bench/bench.py

Nothing is asserted and nothing is skipped when a number comes out badly; the
point of the file is that the table in the README can be regenerated by anyone,
on their own machine, from this repository alone.
"""
from __future__ import annotations

import json
import os
import platform
import random
import secrets
import statistics
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from ss import compliance as CO
from ss import crypto as C
from ss import exchange as EX
from ss import net, ops, zk
from ss.crypto import HashChain, KeyPair, hkdf, merkle_root
from ss.identity import Delegation

HERE = os.path.dirname(os.path.abspath(__file__))


def timed(fn, repeat: int = 5, keep: bool = False) -> dict:
    """Time a callable. The return value is dropped unless it is small and useful.

    Dropping it is not tidiness: a benchmark that keeps the object it just built
    holds a 100 KiB proof per sample and writes it to results.json, which makes
    the results file unreadable for no gain.
    """
    samples = []
    out = None
    for _ in range(repeat):
        t0 = time.perf_counter()
        out = fn()
        samples.append((time.perf_counter() - t0) * 1000.0)
    row = {"ms_median": round(statistics.median(samples), 3),
           "ms_min": round(min(samples), 3), "ms_max": round(max(samples), 3),
           "samples": len(samples)}
    if keep:
        row["value"] = out
    return row


def scalar() -> int:
    return secrets.randbelow(C.group()["q"] - 1) + 1


def bench_crypto() -> list:
    G = C.group()
    rows = []
    rows.append({"name": "group verify (primality, generator order)", "p_bits": 2048,
                 **timed(lambda: C.group.cache_clear() or C.group(), 3)})
    rows.append({"name": "Pedersen commitment (2048-bit group)",
                 **timed(lambda: C.commit(secrets.randbelow(1000)))})
    rows.append({"name": "Ed25519 sign", "n": 200,
                 **timed(lambda: [KeyPair.at(i).sign(b"message") for i in range(200)], 3)})
    rows.append({"name": "Ed25519 verify", "n": 200,
                 **timed(lambda: [C.verify_signature(KeyPair.at(i).public, b"message",
                                                     KeyPair.at(i).sign(b"message"))
                                  for i in range(50)], 3)})
    rows.append({"name": "SHA-256 over 1 MiB", "n": 1,
                 "digest": C.sha256_hex(b"x" * (1 << 20))[:16],
                 **timed(lambda: C.sha256_hex(b"x" * (1 << 20)))})
    return rows


def bench_zk(bits_list=(8, 16, 24)) -> list:
    rows = []
    for bits in bits_list:
        value = min(400, (1 << bits) - 1)
        proof = zk.prove_range(value, scalar(), bits)
        rows.append({"name": "range proof, %d bits" % bits,
                     "bytes": len(json.dumps(proof)),
                     "prove": timed(lambda: zk.prove_range(value, scalar(), bits), 3),
                     "verify": timed(lambda: zk.verify_range(proof), 3)})
    x = scalar()
    G_g = C.group()["g"]
    dlog = zk.prove_dlog("g", G_g, C.powmod(G_g, x, C.group()["p"]), x, {"k": 1})
    rows.append({"name": "Schnorr dlog proof", "bytes": len(json.dumps(dlog)),
                 "prove": timed(lambda: zk.prove_dlog("g", G_g, C.powmod(G_g, x, C.group()["p"]), x, {"k": 1})),
                 "verify": timed(lambda: zk.verify_dlog(dlog))})
    return rows


def bench_exchange(cell_counts=(20, 60, 120), bits: int = 8, repeat: int = 3,
                   wide_cells: int = 60, wide_bits: int = 24) -> list:
    """Round-trip cost as the selection grows, at a narrow and a wide bit width.

    The narrow rows use a register whose per-cell counts are small, because the
    node refuses a sum it can see is out of range and a refused query is not a
    measurement. The wide row uses the same data with a 24-bit range, which is
    what a real deployment would carry: it costs 113 KiB on the wire, so it is
    timed once rather than repeatedly.
    """
    rng = random.Random(20261008)
    regions = ["R%02d" % i for i in range(30)]
    classes = ["class%02d" % i for i in range(10)]
    small = {(r, c): rng.randrange(4) for r in regions for c in classes}
    full = {(r, c): rng.randrange(40) for r in regions for c in classes}
    rows = []

    def make(counts, grant_scope=("query.aggregate",)):
        a = EX.Node("A", "did:sgw:A")
        b = EX.Node("B", "did:sgw:B")
        a.trust(b.did, b.keys.public, b.x25519_public())
        b.trust(a.did, a.keys.public, a.x25519_public())
        bus = EX.Transport()
        bus.register(a)
        bus.register(b)
        b.load(EX.Series.from_counts("outbreak", "cases", counts))
        now = time.time()
        grant = Delegation(grantor=b.did, grantee=a.did, scopes=frozenset(grant_scope),
                           statement_classes=frozenset({"case_count"}),
                           issued_at=now, expires_at=now + 3600).sign(b.keys)
        return a, b, EX.Gateway(a, bus), grant

    for n_cells in cell_counts:
        a, b, gw, grant = make(small)
        want_p = max(1, n_cells // len(classes))
        req = EX.Request(kind="aggregate.bounded", requester=a.did, request_id="b1",
                         series="outbreak", partitions=tuple(regions[:want_p]),
                         subjects=tuple(classes), statement_class="case_count", bits=bits)
        result = gw.ask(b.did, req, [grant])
        if result["receipt"]["status"] != "proved":
            raise SystemExit("benchmark selection refused (%s) at %d cells, %d bits"
                             % (result["receipt"]["reason"], want_p * len(classes), bits))
        rows.append({"name": "exchange round trip, %d cells, %d-bit range"
                              % (len(req.partitions) * len(req.subjects), bits),
                     "cells": len(req.partitions) * len(req.subjects), "bits": bits,
                     "bytes": len(json.dumps(result["receipt"]["payload"]["proof"])),
                     **timed(lambda: gw.ask(b.did, req, [grant]), repeat)})

    a, b, gw, grant = make(full)
    want_p = max(1, wide_cells // len(classes))
    req = EX.Request(kind="aggregate.bounded", requester=a.did, request_id="wide",
                     series="outbreak", partitions=tuple(regions[:want_p]),
                     subjects=tuple(classes), statement_class="case_count", bits=wide_bits)
    wide = gw.ask(b.did, req, [grant])
    if wide["receipt"]["status"] != "proved":
        raise SystemExit("wide benchmark refused (%s)" % wide["receipt"]["reason"])
    rows.append({"name": "exchange round trip, %d cells, %d-bit range"
                          % (len(req.partitions) * len(req.subjects), wide_bits),
                 "cells": len(req.partitions) * len(req.subjects), "bits": wide_bits,
                 "bytes": len(json.dumps(wide["receipt"]["payload"]["proof"])),
                 **timed(lambda: gw.ask(b.did, req, [grant]), 1)})
    return rows


def bench_compliance() -> list:
    ev = CO.Evidence()
    ev.observed("endpoints", [{"name": "gw%d" % i, "tls": 1.3, "refuses_plaintext": True}
                              for i in range(20)])
    ev.observed("accounts", [{"name": "acct%d" % i, "rights": ["store.read"]}
                             for i in range(200)])
    ev.observed("admins", [{"name": "adm%d" % i, "mfa": "hardware",
                            "attested_at": time.time()} for i in range(20)])
    ev.observed("restore_tests", [{"at": time.time() - 86400, "verified": True}])
    ev.observed("stores", [{"name": "s%d" % i, "region": "eu-west"} for i in range(30)])
    ev.observed("vendors", [{"name": "v%d" % i} for i in range(12)])
    chain = HashChain()
    for i in range(500):
        chain.append({"event": "e%d" % i})
    ev.observed("audit_entry_digests", chain.snapshot_heads())
    ev.observed("audit_head", merkle_root(chain.snapshot_heads()))
    ctx = {"jurisdiction": {"allowed_regions": ["eu-west", "eu-north"]}}
    rows = []
    for profile in ("low", "moderate", "high"):
        rep = CO.assess(ev, ctx, profile=profile)
        rows.append({"name": "assess against the %s baseline" % profile,
                     "controls": len(rep.findings),
                     "counts": rep.counts(),
                     **timed(lambda: CO.assess(ev, ctx, profile=profile), 20)})
    rep = CO.assess(ev, ctx, profile="moderate")
    rows.append({"name": "third-party verify of a report",
                 "controls": len(rep.findings),
                 **timed(lambda: CO.verify_report(rep.to_dict()), 20)})
    return rows


def bench_ops(node_counts=(4, 12, 40), rounds: int = 6) -> list:
    rows = []
    for n in node_counts:
        result = ops.replica_run(["n%03d" % i for i in range(n)], rounds=rounds)
        rows.append({"name": "%d replicas, %d partition rounds" % (n, rounds),
                     "operations": result["operations"], "increments": result["increments"],
                     "lost": result["lost"], "converged": result["converged"],
                     **timed(lambda: ops.replica_run(["n%03d" % i for i in range(n)],
                                                     rounds=rounds), 3)})
    return rows


def bench_transport(sizes=(1 << 10, 1 << 16, 1 << 20)) -> list:
    rows = []
    server = net.TcpServer(lambda m: {"len": len(m["payload"])}).start()
    try:
        for size in sizes:
            payload = "x" * size
            rows.append({"name": "one frame over loopback, %d KiB" % (size >> 10),
                         **timed(lambda: net.call("127.0.0.1", server.port,
                                                  {"payload": payload}), 5)})
    finally:
        server.stop()
    server = net.TcpServer(lambda m: {"ok": True},
                           session_factory=lambda: net.SecureSession.pair(
                               hkdf(b"bench-secret", b"session"))[1]).start()
    try:
        shared = hkdf(b"bench-secret", b"session")
        rows.append({"name": "one sealed frame over loopback",
                     **timed(lambda: net.call(
                         "127.0.0.1", server.port, {"verb": "health"},
                         session_factory=lambda: net.SecureSession.pair(shared)[0]), 10)})
    finally:
        server.stop()
    return rows


def environment() -> dict:
    return {"python": sys.version.split()[0], "platform": platform.platform(),
            "machine": platform.machine(), "processor": platform.processor(),
            "cpu_count": os.cpu_count(),
            "pow_backend": C.pow_backend()}


def main(argv=None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    only = argv[0] if argv else None
    builders = {"environment": environment, "crypto": bench_crypto, "zk": bench_zk,
                "exchange": bench_exchange, "compliance": bench_compliance,
                "ops": bench_ops, "transport": bench_transport}
    if only and only not in builders:
        raise SystemExit("unknown section %r; choose one of %s"
                         % (only, ", ".join(sorted(builders))))
    # Only the requested section is built. Building all of them and then
    # discarding the rest means a one-section run pays for the 1024 KiB frame
    # bench and the 40-replica merge, which is how a "quick check" takes minutes.
    chosen = [only] if only else list(builders)
    everything = {}
    for name in chosen:
        t0 = time.perf_counter()
        everything[name] = builders[name]()
        print("  [%s took %.1f s]" % (name, time.perf_counter() - t0),
              file=sys.stderr, flush=True)
    out = os.path.join(HERE, "results.json")
    if only:
        # A single-section run merges into the existing results file rather than
        # leaving the rest of the table unreproducible: `bench.py ops` after a full
        # run replaces the ops rows and keeps everything else.
        merged = {}
        if os.path.exists(out):
            try:
                with open(out, encoding="utf-8") as fh:
                    merged = json.load(fh)
            except Exception:
                merged = {}
        merged.update(everything)
        everything = merged
    with open(out, "w", encoding="utf-8") as fh:
        json.dump(everything, fh, indent=1, sort_keys=False)
    for section, rows in everything.items():
        if section == "environment" and not isinstance(rows, list):
            print("== environment")
            for k, v in rows.items():
                print("   %-12s %s" % (k, v))
            continue
        if isinstance(rows, dict):
            continue
        print("== %s" % section)
        for row in rows:
            name = row.get("name", "?")
            if "verify" in row:
                print("   %-44s prove %8.1f ms   verify %8.1f ms   %7d bytes"
                      % (name, row["prove"]["ms_median"], row["verify"]["ms_median"],
                         row.get("bytes", 0)))
            elif "ms_median" in row:
                extra = ""
                if "controls" in row:
                    extra = "  %d controls" % row["controls"]
                if "lost" in row:
                    extra = "  lost=%d converged=%s ops=%d" % (row["lost"], row["converged"],
                                                              row["operations"])
                print("   %-44s %8.1f ms%s" % (name, row["ms_median"], extra))
    if not only:
        print("\nwritten: %s" % out)
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
